# Generated by Django 5.2.5 on 2025-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailaccount',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='emailaccount',
            old_name='email_password',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='company_name',
        ),
        
        migrations.RemoveField(
            model_name='emailaccount',
            name='use_tls',
        ),
        migrations.RenameField(
    model_name='emailaccount',
    old_name='smtp_host',
    new_name='smtp_server',
),

    ]
