# Generated by Django 5.2.5 on 2025-08-29 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_rename_email_address_emailaccount_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailAccount',
        ),
    ]
