# Generated by Django 5.2.5 on 2025-09-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_alter_emailaccount_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
