# Generated by Django 5.2.5 on 2025-09-01 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremailaccount',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='useremailaccount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='useremailaccount',
            name='password',
            field=models.CharField(default='!@mkvNGjnr23', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremailaccount',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='useremailaccount',
            name='smtp_server',
            field=models.CharField(default='smtp.gmail.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='useremailaccount',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='useremailaccount',
            name='date_added',
        ),
    ]
