# Generated by Django 5.2.5 on 2025-09-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_useremailaccount_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserEmailAccount',
        ),
    ]
